### ISSUE TITLE
DNS Automation request

### ISSUE THREAD

**Issue by owendelong** [socallinuxexpo/scale-network#105]
For combined rooms, can we please (in addition to the AAAA records for the rm209-210 style name) add CNAMES  for the individual room names?

e.g.
rm209-210 IN AAAA 2001:470:f325:503::200:20
rm209 IN CNAME rm209-210
rm210 IN CNAME rm209-210

**Comment by kylerisse** [comment]
yup, ill get them hard coded for now then add them to inventory.py long term

**Comment by owendelong** [comment]
Can we also add switch<n> CNAMEs (e.g. switch4 IN CNAME ballroomde.scale.lan.)

Thanks!

**Comment by kylerisse** [comment]
PR105 submitted with this config, changes deployed
