### ISSUE TITLE
tools

### ISSUE THREAD

**Issue by davidelang** [socallinuxexpo/scale-network#106]
screwdrivers, etc

**Comment by owendelong** [comment]
Please be specific:

1. #2 Philips screwdriver (2)
2. Diagonal cutters (small) (1)
3. Diagonal cutters (medium) (1)

**Comment by davidelang** [comment]
also #3 philips screwdriver (rack mount screws)

**Comment by davidelang** [comment]
#1 Phillips screwdrivers (for juniper modules)

**Comment by owendelong** [comment]
Were ordered as part of our major supply order. Have been received by Steven.
