### ISSUE TITLE
Update existing openwrt build process to reference upstream

### ISSUE THREAD

**Issue by sarcasticadmin** [socallinuxexpo/scale-network#117]
Need to verify that the existing build process still works with the latest upstream changes in openwrt on `wndr3800` APs.

**Comment by davidelang** [comment]
Just a note, I keep seeing talk about the wndr3800 and wndr3700v2 builds being 
depriciated, there is a new build target that we should be moving towards, but 
it's listed as not quite being ready for prime time.

I believe the difference is that the new build is devicetree based.

David Lang
