### ISSUE TITLE
Remove unnecessary udp input module

### ISSUE THREAD

**Issue by sarcasticadmin** [socallinuxexpo/scale-network#125]
Running the following `rsyslogd` config test results in a nonzero return
since we are loading a module that is not actually used. Lets just go ahead
and remove it since its not actually needed on the openwrt APs. See error
below:
```
~# rsyslogd -N1
rsyslogd: version 8.39.0, config validation run (level 1), master config /etc/rsyslog.conf
rsyslogd: imudp: module loaded, but no listeners defined - no input will be gathered [v8.39.0 try http://www.rsyslog.com/e/2212 ]
```

**Comment by davidelang** [comment]
completed
