### ISSUE TITLE
Scratchpad for SCaLE 17x Postmortem issues

### ISSUE THREAD

**Issue by owendelong** [socallinuxexpo/scale-network#136]
This is a new scratchpad ticket. It's intended to allow us to quickly capture items we wish to discuss during the post mortem after the show.

RULES for this issue:

1. ONE ITEM and ONLY ONE ITEM per comment (no monoliths). PLEASE start a new comment for each topic.
2. NO discussion -- If a topic(comment in this issue) warrants an in-issue discussion, start by creating an  issue, then move the discussion into that issue. If you want to provide a pointer to the new issue as a hyperlink within the comment text, that is allowed, even encouraged. 
3. Identify and fix problems, not blame. History can be useful for learning what happened and identifying improvements. It is not about looking back for who was at fault.

**Comment by davidelang** [comment]
see if we can get a few radios for tech earlier, cell/wifi doesn't work in the basement area

**Comment by owendelong** [comment]
For next year buy at least one of these:
https://www.amazon.com/GaffTech-G20NN0-Applicator-Complete-Extension/dp/B0171JYP8K/ref=sr_1_1?keywords=gaffgun&qid=1551896019&s=gateway&sr=8-1
(Test first one and consider buying second one)

**Comment by kylerisse** [comment]
wire maps deployed with switches to avoid having to check with NOC for port assignments

**Comment by kylerisse** [comment]
request monitors be deployed earlier than Wednesday evening for pi/sign validation

**Comment by kylerisse** [comment]
monitoring should be up as soon as possible with switches already defined, switch installations should be validated against monitoring status when deployed

**Comment by kylerisse** [comment]
need way to track people who have requested T-shirts, one person didn't' remember if they filled out the form or not plus no audit trail leaves room for abuse

**Comment by sbibayoff** [comment]
If we don't have the switches/AP's ready by Monday, have paper taped to where they would be placed. So physical network team could place cables(with correct length) where they are needed. This way there is a lesser chance of cable being placed in a wrong place.

**Comment by sbibayoff** [comment]
Have a print out instruction set (1 page) for the physical layout crew which includes port assignments on switches.
example (needs modification):
1) places devices(switches & APs) in correct places
2) connect power & appropriate network cables between devices and switches (on correct ports, list on sheet)
3) Verify, with noc, that the device is seen is good
4) Tape down, after all devices are verified.

Move on

**Comment by sbibayoff** [comment]
An idea, 

Have radios available on Monday, tech is in charge of them till AV shows up on Tuesday, then hand them over tracking and everything else to AV on Tuesday.

**Comment by sbibayoff** [comment]
Maybe third time I'm bringing this up would be the charm,



Label the AP's with their mac address on top. In a large enough size so it could be easily read without having to pick up the AP.

Or, maybe better yet, have a label with a Scale produced s/n , where we would have a list of s/n to mac address.

**Comment by sbibayoff** [comment]
Have power "bars" in the noc. Something like:
https://www.frys.com/product/5960984?site=sr:SEARCH:MAIN_RSLT_PG

Instead of power strips daisy changed and cords all tied up in knots, have 2, 3, or 4 bars on the main table (each plugged into a different outlet/circuit).

Hopefully it would make the cords more manageable.

**Comment by sbibayoff** [comment]
Allocate more physical ports on the switches for AP's. We where running out of AP ports in the IDF's for the AP't that where plugged into the walls, hallways, and such.

I think it would be easier to add a few more ports than configure 3 unique switches.

**Comment by owendelong** [comment]
That’s because we plugged way more APs into the hallways than were supposed to be. e.g. Registration, there were 3 APs that should have been in the Reg switch that went to wall ports for some reason.

Owen

**Comment by hriday** [comment]
I don't think they were plugged into the walls either. I picked up 3 AP's
at reg that were connected to power but had no ethernet lines run.

It was probably missed, but we can get better monitoring next year. Kate
has some amazing diagrams now that Kyle and Steven have enhanced.

**Comment by owendelong** [comment]
Use a single AP Naming convention for Maps, APs, host files, etc.

**Comment by owendelong** [comment]
NOC Power -- Bring in power box and multiple 20A circuits

**Comment by davidelang** [comment]
big TV for the NOC for monitoring

**Comment by owendelong** [comment]
Set up and test flashing stations prior to show. (tested server OS and software)

**Comment by owendelong** [comment]
> Have a print out instruction set (1 page) for the physical layout crew which includes port assignments on switches.
> example (needs modification):
> 
> 1. places devices(switches & APs) in correct places
> 2. connect power & appropriate network cables between devices and switches (on correct ports, list on sheet)
> 3. Verify, with noc, that the device is seen is good
> 4. Tape down, after all devices are verified.
> 
> Move on

This is harder to automate, so it is not addressed by #265 However, I will have printed portmaps ready to tape to the top of each switch this year. PostScript files are auto-generated by the switch configuration code at the same time as the switch configuration files as part of the code in #265.

**Comment by sarcasticadmin** [comment]
Closing as this scratchpad has served its purpose
