### ISSUE TITLE
Renumber and relabel switches

### ISSUE THREAD

**Issue by owendelong** [socallinuxexpo/scale-network#138]
Currently the switch types file is in no logical order by anything rational because the switch numbering doesn't correspond in any way to loudness groups.

I'd like to renumber and relabel the switches into an order that places them in 3 groups (loud, normal, quiet), then reorder the switch types file accordingly.

It does _NOT_ make sense to add this to our workload for the conference, however.

**Comment by sarcasticadmin** [comment]
@owendelong during the last team call you mentioned this was achieved already but I dont remember it being associated with any given PR.

Any context would be greatly appreciated, leaving this open for now.

**Comment by sarcasticadmin** [comment]
Closing as I believe this has already been done or is no longer an issue.
