### ISSUE TITLE
Raspberry Pi Image Instructions

### ISSUE THREAD

**Issue by sarcasticadmin** [socallinuxexpo/scale-network#14]
How do we build the golden image for the pis for the signs, etc.

**Comment by kylerisse** [comment]
mostly written and committed to pi_gold_image branch of scale-network. Will finish tomorrow.

**Comment by kylerisse** [comment]
tomorrow: 
1. disable right click, figure out if we can get rid of openbox completely
2. rebuild and test instructions
3. further QA and tasks

**Comment by kylerisse** [comment]
Instructions are nearly complete. will close this issue and track via the /pi root folder
