### ISSUE TITLE
ansible/inventory.py ignores directives and makes invalid assumptions

### ISSUE THREAD

**Issue by owendelong** [socallinuxexpo/scale-network#149]
In PR #148, the change brings to light the fact that the VLANs files are not being parsed correctly by ansible/inventory.py.

The intent is to parse the "vlans" file only. If that file contains "#include" directives, then only files identified by those directives should be parsed. The switch configuration generator will not process files from "vlans.d" which are not referenced in such a manner and neither should inventory.py.

Further, the directives in VLAN configuration files (whether the master "vlans" file or one of the included files from "vlans.d/" (currently) fall into two categories with different syntax.

Currently, inventory.py simply assumes that every directive is "VLAN" which is invalid. The syntax for a "VVRNG" specification is different and serves a different purpose. This line should not be commented out as it affects the config generation for switches affected by a file in "types/" which contains a "VVLAN" directive (currently only "types/Booth").

The correct approach is to compare the first field of each line (directive) in the file to a known directive understood by the parser. If the directive in question is not understood, the safest action for the parser to take is to emit a warning and ignore the line.

**Comment by owendelong** [comment]
See https://github.com/socallinuxexpo/scale-network/blob/master/switch-configuration/README.md for complete documentation of the configuration files and how they should be parsed and interpreted as well as documentation of all valid directives.

**Comment by kylerisse** [comment]
Good call, we should process the file as intended. This should come after #144 and #153 .

**Comment by kylerisse** [comment]
Suggestions for added error handling https://github.com/socallinuxexpo/scale-network/pull/158#discussion_r261841739

**Comment by owendelong** [comment]
I believe this is resolved... Kyle, can you verify and if so, close this issue?
