### ISSUE TITLE
Pre 16x Shopping List

### ISSUE THREAD

**Issue by sarcasticadmin** [socallinuxexpo/scale-network#16]
What does the Tech team need to order before the week of the conference?

**Current List**
1. Box of gaffer tape
2. 5 or more 6' HDMI cables
3. 8 DVI to DVI monitor cables
4. Some amount of SFP modules (@owendelong will figure this out)
5. Blue tape

**Comment by kidicarus2** [comment]
Was the gaffer tape ordered?

To Your Success
- Steven

**Comment by kylerisse** [comment]
We need more than 5 or more 6' HDMI cables. Last year we had to borrow from the AV team for a few of the facility supplied televisions. Can't guarantee their availability.

**Comment by owendelong** [comment]
I was told that it was, but I will confirm. If not, I will order it along with HDMI and DVI cables.

* 8 DVI to DVI monitor cables

**Comment by sarcasticadmin** [comment]
Thanks everyone! I updated the list

**Comment by owendelong** [comment]
OK.. I'm closing out the shopping list and placing the order now. Anything added below here likely won't get ordered for the show.

**Comment by sbibayoff** [comment]
If it's now too late:
Threshold hold Gaffers tape (yellow, with black stripes), - 2 roles

**Comment by owendelong** [comment]
It should be, but I happened to glance at this just before submitting the order.

I’ll add it.

Owen

**Comment by owendelong** [comment]
Added 2 rolls of caution striped yellow/black gaffer tape (3") to the list per Steve Bibayoff's request.

**Comment by owendelong** [comment]
Order has been placed for all items above this marker.
