### ISSUE TITLE
Modify flash.sh to support freebsd

### ISSUE THREAD

**Issue by sarcasticadmin** [socallinuxexpo/scale-network#174]
`flash.sh` does not fully support freebsd.

two known issues are:
* waiting for AP to become ping-able. `down expect_continue` (or something like this)
* arp is not being parsed correctly

**Comment by owendelong** [comment]
Assigning to Rob because he's the only one who cares.

**Comment by owendelong** [comment]
If this isn't fixed by Feature Freeze, I'll close it wont fix.

**Comment by sarcasticadmin** [comment]
Closing as this hasnt been an issue, especially with my primary flashing machine being linux now :laughing:
