### ISSUE TITLE
start show setup with an AP set to proxy to wifi WAN

### ISSUE THREAD

**Issue by davidelang** [socallinuxexpo/scale-network#177]
There are a number of things that can't be done without network access, and servers don't have wifi so can't be teathered to a phone.

So rather than having everyone stuck until the network is up, have an AP setup so that it can connect to a wifi signal as it's WAN (either the facility or a phone) and provide wired network connectivity.

**Comment by sarcasticadmin** [comment]
During the last work party we built a dedicated AP for the wifi proxy to conference LAN for monday. We can close this when we have it configured and working during the show

**Comment by owendelong** [comment]
This was completed but didn't get used as the wired network to the NOC came up early on.
