### ISSUE TITLE
add AV lan to AP trunk (at least for AV switch)

### ISSUE THREAD

**Issue by davidelang** [socallinuxexpo/scale-network#190]
The APs in the AV room need to be able to connect to the AV VLAN

need to discuss if the AV lan should be available outside of the AV room, what are the AV team using this for, how bad would it be if this was available everywhere? does it need to be a separate SSID?, etc.

**Comment by owendelong** [comment]
Resolved for SCaLE 17x in od.17.11

**Comment by owendelong** [comment]
This is already completed.
