### ISSUE TITLE
rdnssd on pis

### ISSUE THREAD

**Issue by kylerisse** [socallinuxexpo/scale-network#208]
pis can't take advantage of RFC5006 which can be resolved by running rdnssd

**Comment by owendelong** [comment]
Correction -- RFC 6106 (Obsoletes 5006).

**Comment by kylerisse** [comment]
let's capture this requirement in #256

**Comment by sarcasticadmin** [comment]
@kylerisse was this completed in #290 ?

**Comment by owendelong** [comment]
Tested and working on PI4 General image.
