### ISSUE TITLE
improve zabbix performance

### ISSUE THREAD

**Issue by davidelang** [socallinuxexpo/scale-network#227]
look at the scripts in /etc/zabbix_agentd.d/* and see if it's possible to replace lots of separate calls to iwinfo (and zabbix_helper_mac80211) with a script that makes one call to iwinfo and parses all the data needed to send it to the zabbix server via zabbix_sender, then sleeps and repeats.

**Comment by sarcasticadmin** [comment]
Additionally we might need to remove some additional pkgs for zabbix: https://github.com/socallinuxexpo/scale-network/blob/master/openwrt/configs/common.config#L64-L66

**Comment by owendelong** [comment]
Zabbix is deprecated, closing won't fix.
