### ISSUE TITLE
new APs don't support DFS channels

### ISSUE THREAD

**Issue by davidelang** [socallinuxexpo/scale-network#236]
the current build of OpenWRT isn't supporting DFS channels, to the point where if you configure it to use a DFS channel, the 5G radio won't work until you power cycle, even if you select a different channel.

**Comment by sarcasticadmin** [comment]
Due to #281 this wont happen for Scale18x

**Comment by sarcasticadmin** [comment]
Closing as this seemed to be specific to TPlink C2600 which will no longer be the successor in AP hardware.
