### ISSUE TITLE
Buy gaffer tape

### ISSUE THREAD

**Issue by owendelong** [socallinuxexpo/scale-network#248]

**Comment by owendelong** [comment]
https://smile.amazon.com/ProTapes-Pro-Premium-Gaffers-Adhesive/dp/B00DYB2TTC/ref=sr_1_2_sspa?keywords=gaffer+tape+box&qid=1567731889&s=gateway&sr=8-2-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExSlBFTEg0TE9STUEmZW5jcnlwdGVkSWQ9QTAzNjkwMDgyMDBLUURJVDE2RFJJJmVuY3J5cHRlZEFkSWQ9QTAwMDE2MzJPVTVZTDdVOVAxREQmd2lkZ2V0TmFtZT1zcF9hdGYmYWN0aW9uPWNsaWNrUmVkaXJlY3QmZG9Ob3RMb2dDbGljaz10cnVl

Will send to Ilan/Bala for purchase

**Comment by hriday** [comment]
I thought we had a ton of gaffer tape?

**Comment by owendelong** [comment]
Two years ago, we bought a ton of gaffer tape (a box, as described below).

One year ago, we had half a ton of gaffer tape left.

This year, it is mostly gone.  We use roughly half a box of gaffer tape per year. This has been communicated more than once.

It’s been two years since we bought gaffer tape, thus, it’s time to order again.

Owen

**Comment by owendelong** [comment]
Steven, Please confirm this was received. If so, please close this issue.

**Comment by kidicarus2** [comment]
Confirmed it is received,

unknown how to close issues.

thanks

To Your Success!
Steven
