### ISSUE TITLE
Create build procedure for Pi 4B

### ISSUE THREAD

**Issue by kylerisse** [socallinuxexpo/scale-network#256]
Create and document build procedure for Pi 4B images

**Comment by sarcasticadmin** [comment]
Interesting project I came across the other day: https://buildroot.org/

I dont think we have time to address the build process with this particular approach but I think this might be something to consider for post-18x

**Comment by owendelong** [comment]
For things like this, please create a new issue and tag the new issue with post-18 or something like that.

Owen

**Comment by sarcasticadmin** [comment]
`buildroot` issue can be found here: https://github.com/socallinuxexpo/scale-network/issues/271

**Comment by kylerisse** [comment]
The acceptance criteria for this task is to product 3 distinct image files for pis with use case profiles:
- Registration / Signs
- Flashing
- Helpdesk

**Comment by kylerisse** [comment]
Further acceptance criteria includes:
- imaging PIs have no network or gui and aren't part of the further requirements in this list.
- all pis should have zabbix agent
- test 3 different monitor types (4k, 1080p, and [scale monitors])
- LLDP enabled, validated by juniper switch
- signs / registration using existing python browser setup (detect mouse)
- priority order is flashing station > everything else
- pis should get their names from dhcp

**Comment by owendelong** [comment]
Registration/Sign PI image must meet the requirements in #239.

Ideally:

1. PI detects whether wired connection has a DHCP server.
- 1. If not, Connect wirelessly to Registration VLAN and bridge Wired port
- 2. If so, disable WiFi Interface and operate normally.
2. If PI is operating in bridged mode, WiFi is the upstream interface. Printer will be attached to wired interface.
- 1. PI should ascertain printer's IP address (snoop the bridged DHCP transaction between printer and DHCP server)
- 2. PI should send all badges to the detected attached printer.

The purpose of this is to have a self-contained registration station which does not depend on the registration switch or any of the wired infrastructure other than having a working AP within range. This will allow us do most of the registration tear-down earlier on Sunday.

**Comment by davidelang** [comment]
I think it's simpler to just wire to the AP, it only adds one more wire

we already have the multi-network config support in the APs.

We have an AP in the area of the help desk, so we should be able to hook up one 
printer and pi to the AP rather than the reg switch.

David Lang

**Comment by owendelong** [comment]
OK... Let's go with that for this year.
