### ISSUE TITLE
Make CSV files compatible with GitHub beautification

### ISSUE THREAD

**Issue by owendelong** [socallinuxexpo/scale-network#258]
There's a standard for header lines and documentation lines that GitHub expects in CSVs.

If we make our CSV files compatible with those, then GitHub will beautify them for us when viewed in the web interface. This would be useful.

It's not urgent.

**Comment by kylerisse** [comment]
great idea, I'll handle it in the next pass on these

**Comment by sarcasticadmin** [comment]
This shows up when you look at the `.csv`'s but I figure Id add it here for ref: https://help.github.com/en/articles/rendering-csv-and-tsv-data
