### ISSUE TITLE
Provision new server hardware

### ISSUE THREAD

**Issue by sarcasticadmin** [socallinuxexpo/scale-network#268]
## Description

We have new hardware that was donated very generously by ixsystems.com . This will replace the majority of standalone desktop machines that were previous fulfilling roles as "servers" from previous conferences.

Were going to be running the following configuration on the hardware:

* Base OS: FreeBSD
* Hypervisor: Bhyve
* Individual VMs for each server role

## Acceptance Criteria
* Servers are up and running with consistent builds via ansible
* VMs are stable and provisioning has been tested for all existing roles
* Network interfaces and bridges are correctly working with both IPv4 and IPv6

**Comment by kylerisse** [comment]
Additional acceptance criteria:
- all vms running

**Comment by sarcasticadmin** [comment]
Completed as of #302
