### ISSUE TITLE
Create simple pytest framework for ansible inventory

### ISSUE THREAD

**Issue by sarcasticadmin** [socallinuxexpo/scale-network#273]
## Description

https://github.com/socallinuxexpo/scale-network/blob/master/ansible/inventory.py has become an important glue for the majority of provisioning and inquiries into the provisioned hardware. We should take the necessary steps to add a `pytest` framework to start validating on the parsing of our inventory.

## Acceptance Criteria
* Added framework for `pytest` and `tox`
* Integrated that into the CI test suite
* Spun out follow up issues as needed

**Comment by kylerisse** [comment]
I have a WAIT PR up for this @sarcasticadmin . Please take a look and let me know if you like the approach. I did not include tox since we only use python3 and my test container has pytest, so I'm not sure if we need it yet. Appreciate any feedback and guidance. Thanks!
