### ISSUE TITLE
Add validation tests to tsv files

### ISSUE THREAD

**Issue by kylerisse** [socallinuxexpo/scale-network#278]
## Description
Follow up to #274 for all the TSV files used by switch configuration scripts and Ansible inventory. Extend the existing datasources workflow.

## Acceptance Criteria
Validation of the following files as part of the CI pipeline:
- switchtypes
- types/*
- vlans
- vlans/*

**Comment by kylerisse** [comment]
@owendelong can you please confirm this acceptance criteria captures all the necessary files? I omitted the defaults and booth_list.tsv files since I don't believe them to be defined in scripts. Please us know if I've missed any files that need to be added for testing. Thank you!

**Comment by owendelong** [comment]
Yes… That is a complete list.

Owen
