### ISSUE TITLE
Investigate ath10k-ct driver solutions

### ISSUE THREAD

**Issue by sarcasticadmin** [socallinuxexpo/scale-network#281]
## Description

Related to the finding during #264 and currently seeing issue for the TPLINK C2600

Dumping ground for notes around this issue:
* https://github.com/openwrt/openwrt/blob/db992e7b53f5a3b614c27f9f2d589128c570a821/package/kernel/ath10k-ct/Makefile 
* http://lists.infradead.org/pipermail/openwrt-devel/2020-January/021482.html
* https://github.com/openwrt/openwrt/pull/1077
* https://bugs.openwrt.org/index.php?do=details&task_id=2664

## Acceptance Criteria
* Resolve the issues with the ath10k-ct driver

**Comment by owendelong** [comment]
We're going to skip this for SCaLE 18x and only support the Netgear Routers this SCaLE.

**Comment by sarcasticadmin** [comment]
Progress on 10k, courtesy of @davidelang:

1. https://forum.openwrt.org/t/aql-and-the-ath10k-is-lovely/59002
2. http://lists.infradead.org/pipermail/openwrt-devel/2020-March/022412.html
3. http://lists.infradead.org/pipermail/openwrt-devel/2020-March/022411.html

**Comment by sarcasticadmin** [comment]
The saga continues for these small devices. This could effect our our tplinks too:

- https://bugs.openwrt.org/index.php?do=details&task_id=2651#comment8515

**Comment by sarcasticadmin** [comment]
most recently, looks like there some instability with 5.4 kernel on the  c2600. It seems like you need to disable cpufreq at build to keep it from crashing: https://bugs.openwrt.org/index.php?do=details&task_id=3099#comment8901

**Comment by davidelang** [comment]
locking the devices to full speed rather than trying to save power doesn't seem 
like a big problem to me :-)

**Comment by sarcasticadmin** [comment]
Were most likely going to forego adopting the C2600 due to its track record of instability, going to close this since well be focusing on the newer hardware as part of #410
