### ISSUE TITLE
Remove snmpd on openwrt

### ISSUE THREAD

**Issue by sarcasticadmin** [socallinuxexpo/scale-network#32]
~Look at old config from previous years and incorporate it into this years build process~

Update: After the problem with usage during 17x with the snmp daemon, weve opted to remove it from build

**Comment by davidelang** [comment]
most of the data we were gathering via snmp is now being gathered by zabbix

**Comment by sarcasticadmin** [comment]
After the problem with usage during 17x with the snmp daemon, weve opted to remove it from build

**Comment by owendelong** [comment]
Can this issue be closed?

**Comment by sarcasticadmin** [comment]
No this was installed on the image for 17x, and it looks like its still in there: https://github.com/socallinuxexpo/scale-network/blob/master/openwrt/configs/common.config#L61
