### ISSUE TITLE
Build process and supporting scripts to gather info on running pi and update dns

### ISSUE THREAD

**Issue by davidelang** [socallinuxexpo/scale-network#344]
## Description
the pis will come up with good lldp hostnames, but it needs to be added to dns

make it so that when the pi comes up, it hits a service (web page or similar). that service then does a ssh to the IP address that hit it and runs the following

#!/bin/bash
echo -n "hostname,"; hostname
echo "ifconfig ========"
ifconfig -a
echo "lldpinfo ========"
lldpcli show n
lldpcli show ch
lldpcli show i
echo "xrandr ========"
xrandr --display:0

it gathers the hostname from this and sets it in dns for the pi

sanity checking of the hostname, and the source network is needed (reg, signs, staff allowed)

**Comment by sarcasticadmin** [comment]
The pis are already set in DNS via facts defined here: https://github.com/socallinuxexpo/scale-network/blob/40a3d088552ba48b4e334823f4a521f4fc796c14/facts/pi/pilist.csv
