### ISSUE TITLE
write script to populate zabbix maps from external position mapping data

### ISSUE THREAD

**Issue by davidelang** [socallinuxexpo/scale-network#349]
here are examples of a map with a couple hosts and links. a map can be created externally like this and imported, or the map can be built on the fly via the api

[zbx_export_sysmaps.xml.txt](https://github.com/socallinuxexpo/scale-network/files/4301516/zbx_export_sysmaps.xml.txt)

## Description
Brief description of the Issue

## Acceptance Criteria
What is the expected outcome that resolves this issue?

**Comment by sarcasticadmin** [comment]
closing since we no longer have zabbix
