### ISSUE TITLE
High Temps in switches indicate need for cleaning

### ISSUE THREAD

**Issue by davidelang** [socallinuxexpo/scale-network#350]
11:34:47 AM				CTF4.scale.lan	FPC: EX4200-48P, 48 POE @ 0/*/*: Temperature is above warning threshold: >50	25m 32s	No	
11:34:47 AM				CTF4.scale.lan	Routing Engine 0: Temperature is above warning threshold: >50

**Comment by owendelong** [comment]
Let's plan on opening and vacuuming all of the Juniper switches at the first work party for next year.

**Comment by owendelong** [comment]
http://monitoring1.scale.lan/zabbix/latest.php?groupids%5B%5D=16&application=Temperature&select=&filter_set=1

Indicates that the problem is affecting more than one switch.

**Comment by sarcasticadmin** [comment]
@owendelong IIRC we checked the switches during last years work party and they were all clean.

Going to close but let me know if we need to reopen for the upcoming work party.
