### ISSUE TITLE
Generate SSH key for administrative SSH access

### ISSUE THREAD

**Issue by sarcasticadmin** [socallinuxexpo/scale-network#387]
## Description

Relates to: https://github.com/socallinuxexpo/scale-network/issues/359

Make the that the key we generate is compatible with the SSH servers we are trying to connect to. Consider things like key type and size. Well need to make sure that the following SSH servers:
- Juniper switches
```
# ssh -V
OpenSSH_6.9, SSH protocols 1.5/2.0, OpenSSL 1.0.2k  26 Jan 2017
SSH release 15.1R6.7 built by builder on 2017-04-22 23:50:34 UTC
# uname -a
JUNOS 49 15.1R6.7 JUNOS 15.1R6.7 #0: 2017-04-23 01:54:31 UTC     builder@svl-junos-p001:/volume/build/junos/15.1/release/15.1R6.7/obj/powerpc/junos/bsd/kernels/JUNIPER-EX/kernel  powerpc
```
- Openwrt APs
- Servers

UPDATE:
- Will leverage ed25519 key for this purpose based on comments below: https://github.com/socallinuxexpo/scale-network/issues/387#issuecomment-1024749803
- Key type seems to be well supports >= OpenSSH 6.5

## Acceptance Criteria
- Add the public key to the source of truth for our SSH keys, if https://github.com/socallinuxexpo/scale-network/issues/359 is completed first then this will be a central location
- Store the SSH private key in a save place and share it with the maintainers of the tech team

**Comment by owendelong** [comment]
I believe that everything should support ED25519 at this point.

If that's the case, I propose using the ED25519 standard.

I would also suggest that this key should rotate at code freeze for each conference.

**Comment by sarcasticadmin** [comment]
> I believe that everything should support ED25519 at this point.

@owendelong I agree, I think we pretty much on a current version of OpenSSH for the APs and the linux boxes will be fairly up to date as well.

Dont we already have a key for this? I thought you generated it as the 3rd work party. If not I can generate one for this use case.
