### ISSUE TITLE
Disable password SSH login on switch production configurations

### ISSUE THREAD

**Issue by sarcasticadmin** [socallinuxexpo/scale-network#389]
## Description

Relates to #387

We should disable password ssh login for our juniper switch production configurations. I think we would still have to have a password for the login via serial for physically connecting to the switch.

## Acceptance Criteria
- Disable password ssh login in our switch config for production images
- Ensure that console connectivity still works as expected

**Comment by davidelang** [comment]
I agree.

David Lang

**Comment by owendelong** [comment]
It’s not clear to me that this is possible. Will require investigation.

To the best of my knowledge, user configuration on the Juniper switch does not allow for distinction between authentication methods allowed by access methodology.

Owen

**Comment by owendelong** [comment]
This turns out to be quite simple... set system services ssh no-passwords, so I will add it to the protoconfig template.

**Comment by owendelong** [comment]
Resolved via PR#662
