### ISSUE TITLE
zabbix-sender on openwrt image

### ISSUE THREAD

**Issue by kylerisse** [socallinuxexpo/scale-network#420]
## Description
One concern that came up with #415 is the removal of zabbix-sender due to it's reliance on zabbix server as a dependency. Investigate a way to install the package, ensuring that the server dependencies are not included in the image if possible.

## Acceptance Criteria
zabbix-sender is back in the openwrt image, ideally without any zabbix server dependencies.

**Comment by owendelong** [comment]
I believe we're deprecating Zabbix in favor of Prometheus at this point, so I think this has been rendered moot.
