### ISSUE TITLE
Determine Pi placement and network config for Reg stations and Signs

### ISSUE THREAD

**Issue by kylerisse** [socallinuxexpo/scale-network#428]
## Description
Since we're moving back to the LAX Hilton for 2022, we'll need to determine where the signs and regdesk Pis will connect to the network. There are network switch considerations, which are related to #425 as well as cable planning.

## Acceptance Criteria

- Team has a map with locations for each sign and reg station as well as supporting [switch configuration](https://github.com/socallinuxexpo/scale-network/tree/master/switch-configuration/config)

**Comment by owendelong** [comment]
Completed
