### ISSUE TITLE
Physical cable layout diagrams for LAX Hilton rooms

### ISSUE THREAD

**Issue by kylerisse** [socallinuxexpo/scale-network#430]
## Description
Given the move to LAX Hilton, we probably need room layout diagrams with locations indicated for switches, AV equipment, APs, jacks (cable and power), and required network cable lengths. This might exist from previous Hilton events. This issue ties directly into #425 #427 and #428 . There also needs to be somebody responsible for the gear being deployed.

## Acceptance Criteria
Diagrams with physical equipment locations in public spaces exist and a plan to roll out this equipment is clear, including who is responsible for actually placing the equipment.

**Comment by owendelong** [comment]
Overtaken by events.
