### ISSUE TITLE
Document Pre Conference Checklist for repo

### ISSUE THREAD

**Issue by sarcasticadmin** [socallinuxexpo/scale-network#434]
## Description

Wanting to track and eventually added an official doc to the repo to capture the pre conference checklist for the repo. Current we have:

1. Update admin keys and related tests
2. Eliminate admin and staff WiFi SSIDs.
3. Update network team members keys (https://github.com/socallinuxexpo/scale-network/tree/master/facts/keys) if necessary
4. Update `scale` version in `facts/secrets/*-openwrt-example.yaml` 
5. Update wifi and root secrets in `facts/secrets/*-openwrt-example.yaml` 
6. Update scale-signs repo per: https://github.com/socallinuxexpo/scale-signs#yearly-tasks
7. Create release: https://github.com/socallinuxexpo/scale-network/blob/master/RELEASE.md

## Acceptance Criteria
- Document describing all steps that need to be taken prior to the networking team showing up to the conference

**Comment by owendelong** [comment]
Switch Configuration completed for step 2. Routers will get updated at show.

**Comment by sarcasticadmin** [comment]
Completed as for #640
