### ISSUE TITLE
computers on scale-public-slow can't resolve hostnames

### ISSUE THREAD

**Issue by jaymzh** [socallinuxexpo/scale-network#478]
## Description
Much like yesterday - computers on scale-public-slow can't resolve hostnames. In this case the VAX check Pi's as well as my laptop

The Pi's can't find -fast (maybe don't support 5ghz?)

## Acceptance Criteria
It works

**Comment by owendelong** [comment]
The pis do support 5Ghz, but they might not see it in that location.

**Comment by jaymzh** [comment]
FYI

74:44:01:93:75:D4 - is bad
C4:04:15:90:1B:D3 - is good

**Comment by owendelong** [comment]
74:44:01:93:75:d4 is upstairs off of santamonicab (santamonicab-3) -- It's far from the vaxdesk.
c4:04:15:90:1b:d3 is on the stairwell and is probably the best location to serve vaxdesk from.

**Comment by jaymzh** [comment]
Rob fixed the bad one. thanks!
