### ISSUE TITLE
aplist conversion file throws away the first line

### ISSUE THREAD

**Issue by davidelang** [socallinuxexpo/scale-network#494]
the conversion from aplist.csv to dhcpd.conf.hosts assumes the first line is a header and throws it away.

it should do sanity checking to see if it is a header or data and only ignore it if it's a header

**Comment by owendelong** [comment]
Preferred behavior IMHO is to have a comment character or leadin (e.g. # or // or ;) and have the parser strip those in the first pass. Header should be expressed as a comment.

**Comment by owendelong** [comment]
Has this been resolved at this point?

**Comment by sarcasticadmin** [comment]
I would agree with @owendelong 

We can close this as the process for generating the `kea.conf` has dramatically changed since we were using `isc-dhcpd` and `dhcpd.conf`
