### ISSUE TITLE
Dedicated loghost for rsyslog log aggregation

### ISSUE THREAD

**Issue by sarcasticadmin** [socallinuxexpo/scale-network#508]
## Description
Historically this was setup on `server3` (alias `bigbrother` or `monitoring` server). See DNS entries here: https://github.com/socallinuxexpo/scale-network/blob/19c9238e7482b35ca9bef3673919005fc21ff895/facts/servers/examples/dns/db.scale.lan.records.servers#L16-L18

It would be nice to have a dedicated machine for aggregating logs since the monitoring server still has to be figured out along with existing items like: https://github.com/socallinuxexpo/scale-network/issues/240 and the load requirements are already on the high side.

This loghost machine will also provide as good proving ground for getting together our framework for building and deploying with nixos instead of ansible.

## Acceptance Criteria
- Create a machine that provides a minimal rsyslog server to support existing log aggregation needs by scale-network

**Comment by davidelang** [comment]
one of the reasons for useing the monitoring server for logging is that there 
are things that show up in the logs that we want to scrape and graph, or 
otherwise report

not that it can't be done on a separate VM, just explaining why it was done this 
way to begin with.

David Lang

**Comment by sarcasticadmin** [comment]
Thanks @davidelang for the clarification, that makes sense based on the past conferences

**Comment by owendelong** [comment]
I’m going to suggest an alternative here. What if we had a dedicated instance for persistent storage that was shared across all VMs. Dedicated log server would write logs to a section of that server for logs, but others could read it for scraping/graphing/etc.This would only be for things we want to store persistently across years/upgrades/etc. In this way, all of the other VMs could undergo “bare metal” rebuilds without worrying about preserving content/config. Config would either come from the git repo and content would be in persistent storage. Thoughts?On Dec 23, 2022, at 23:44, Robert James Hernandez ***@***.***> wrote:﻿
Thanks @davidelang for the clarification, that makes sense based on the past conferences
