### ISSUE TITLE
Run simple nix fmt and flake ci checks

### ISSUE THREAD

**Issue by sarcasticadmin** [socallinuxexpo/scale-network#510]
## Description

relates to: https://github.com/socallinuxexpo/scale-network/issues/738

As we add more nix configuration to this repo it would be nice to start out with some initial tests for sanity: `nixpkgs-fmt` and `flakes check` would be a good start

## Acceptance Criteria
- github actions runs `nixpkgs-fmt` and `flakes check` for any nix code changes

**Comment by nixinator** [comment]
https://github.com/kamadorueda/alejandra

seems to be the formater of choice.. 

but nixfmt is also good.

**Comment by sarcasticadmin** [comment]
@nixinator hadnt heard about alejandra before, will definitely check this out too!
