### ISSUE TITLE
Convert /tux keyword action to use standardize-pr-comment

### ISSUE THREAD

**Issue by sarcasticadmin** [socallinuxexpo/scale-network#511]
## Description

Currently we are only able to test changes to https://github.com/socallinuxexpo/scale-network/blob/master/.github/workflows/trigger.yml after it lands in `master` due to the way the action triggers out of the box from github actions.

The upstream project: https://github.com/Nebulaworks/action-standardize-pr-comment provides a way of unifying the comment apis provided by actions so that PRs that effect the comment APIs inside the action can be tested before landing in `master`.

## Acceptance Criteria
- trigger.yml action now has the ability to be triggered during an open PR

**Comment by owendelong** [comment]
Yes, please!!

Owen
