### ISSUE TITLE
remove ansible-test from CI

### ISSUE THREAD

**Issue by kylerisse** [socallinuxexpo/scale-network#590]
## Description
Now that we're on NixOS, no need for Ansible testing in CI. We need to validate data files still though https://github.com/socallinuxexpo/scale-network/blob/master/.github/workflows/ansible-test.yml#L19-L34

## Acceptance Criteria
- `ansible-test` job removed from https://github.com/socallinuxexpo/scale-network/blob/master/.github/workflows/ansible-test.yml
- file renamed to `validate-datafile.yml` 
- name renamed to `validate-datafile`
- `- 'ansible/**'` removed from path

**Comment by sarcasticadmin** [comment]
Closed via #622
