### ISSUE TITLE
enable dhcpv6 server for kea on core machine

### ISSUE THREAD

**Issue by sarcasticadmin** [socallinuxexpo/scale-network#596]
## Description

Relates to: https://github.com/socallinuxexpo/scale-network/issues/392

Kea config is currently only v4. Need to add our v6 version of the config.

## Acceptance Criteria
- Kea service running on core provides dhcpv6 server
- Appropriate vm test to match

**Comment by nixinator** [comment]
Just our of curiosity, i thought V6 address were big enough so you don't need dhcp at all, and one less service is one less thing to go wrong?

**Comment by davidelang** [comment]
we are passing some parameters via dhcp, so those are still needed.

David Lang

**Comment by sarcasticadmin** [comment]
@nixinator Yes @davidelang is correct. Ultimately well we passing the v4 options via v6.

IIRC @owendelong had some other use cases for this as well

**Comment by owendelong** [comment]
Yes... Sometimes you want a particular host to consistently get the same address. While EUI-64 sort of allows this, it's no longer default on the vast majority of systems. Using DHCP6 reservations provides a consistent way to manage these addresses.
