### ISSUE TITLE
Consider Mikrotik hPA ax2 as a candidate for new APs

### ISSUE THREAD

**Issue by owendelong** [socallinuxexpo/scale-network#604]
## Description
Mikrotik has released the hAP ax2 for $99.

PoE in and out (limited), ARM 64 quad core IPQ-6010 864Mhz, 1G Ram, 128M Flash.
Intended to run RouterOS, but predecessor (hPA ac2) is on the supported hardware list for OpenWRT, and from the looks of it, only the radios changed for the ax version.

## Acceptance Criteria
Decide whether this is a desirable alternative to or augmentation to the Belkin/Linksys model that is our current frontrunner.

**Comment by sarcasticadmin** [comment]
Closing as we have decided on using and currently support the Belkin RT3200 (Linksys E8450) https://github.com/socallinuxexpo/scale-network/issues/532
