### ISSUE TITLE
Rename gha workflow to match existing functionality 

### ISSUE THREAD

**Issue by sarcasticadmin** [socallinuxexpo/scale-network#630]
## Description

Currently we have validate-datafiles.yml: https://github.com/socallinuxexpo/scale-network/tree/4699e5e24d6dc3fe9dfc137c83218290ad84c322/.github/workflows but this contains not only the pytest for validation but additional tests to leverage the nix job cache. This results in our entire CI running in under 60 seconds for every change vs have to specify the paths like our previous CI workflows.

Given how expressive we can be via the tests inside the our nix configuration: https://github.com/socallinuxexpo/scale-network/blob/4699e5e24d6dc3fe9dfc137c83218290ad84c322/nix/tests/flake-module.nix I dont see much need for separate CI workflows and the typical features you would require for a workflow.

I would purpose we move rename `validate-datafiles.yml` to `ci.yml` or something generic and just continue to add out runs to the single job. 

## Acceptance Criteria
- ci.yml contains all ci jobs that we have

**Comment by owendelong** [comment]
Seems reasonable to me... Please make it so and close issue.
