### ISSUE TITLE
caption vm for AV

### ISSUE THREAD

**Issue by sarcasticadmin** [socallinuxexpo/scale-network#679]
## Description

A VM that has access from the attendees' WiFi and has incoming access from the AV network.

Agreed upon requirements:

```
2 CPUs
4GB of ram
40GB of disk
Ubuntu 22.04
port 80 (html) open for access to the attendees and some other port open to the A/V network
```

@owendelong is aware of this for 21x

## Acceptance Criteria
- vm deployed to hypervisor1 (hypervisor conference) per requirements
- DNS entry pointing to:  `captions.scale.lan`

**Comment by owendelong** [comment]
Please plan on implementing the port limitations via nft or iptables running on the machine (preferably iptables-legacy if I get to choose).

**Comment by sarcasticadmin** [comment]
Im leaving the OS configuration up to the AV team to configure

**Comment by owendelong** [comment]
That’s fine as long as they are informed that they are responsible for any filtering they want.

Owen

**Comment by sarcasticadmin** [comment]
Closing as this was completed and AV was able to use the VM during the expo
