### ISSUE TITLE
shell-isms for sanity

### ISSUE THREAD

**Issue by sarcasticadmin** [socallinuxexpo/scale-network#694]
## Description

We need to include the following configs within all of our nix machines:

  - vim mouse disabled: `set mouse-=a`
  - date local should be in military time instead of am/pm

probably easiest to add it to [_common/base.nix](https://github.com/socallinuxexpo/scale-network/blob/master/nix/machines/_common/base.nix)

## Acceptance Criteria
- @owendelong approves of config

**Comment by davidelang** [comment]
I agree with both.
