### ISSUE TITLE
sign resolution 'problems'

### ISSUE THREAD

**Issue by davidelang** [socallinuxexpo/scale-network#712]
on 1080p resolution screen, the current sign works reasonably well, but with the priority to show vendor logos and twitter comments, very little schedule information can be displayed

now that 4k screens are the default, we can make better use of the space.

option 1, we can keep the logos reasonable, go to larger fonts, and add many additional lines of scheduling data

option 2. switch to portrait mode, make the fonts a little larger, and add many more additional lines of scheduling data

In my experience, schedule data works much better in portrait mode as more is displayed, and with a scrolling display, the data is on the screen for a longer time, so you can scroll a bit faster and still give people lots of time to read the details as it moves up the screen.

**Comment by sarcasticadmin** [comment]
Weve opted to scale the display given resolutions detected on the display https://github.com/socallinuxexpo/scale-kiosk/pull/13
