### ISSUE TITLE
Expo Hall network drop

### ISSUE THREAD

**Issue by ptrlow1** [socallinuxexpo/scale-network#713]
## Description
Brief description of the Issue
Wire drops at the expo hall

## Acceptance Criteria
What is the expected outcome that resolves this issue?

- [ ] 1 port Booth 312 Coder
- [ ] 2 ports Booth 313 Datadog
- [ ] 1 port Booth 103 SUSE
- [ ] 1 port Booth 432 Shell On Demand Appliance

**Comment by owendelong** [comment]
Each booth gets a separate issue.
