### ISSUE TITLE
test 3d prints for drive trays

### ISSUE THREAD

**Issue by sarcasticadmin** [socallinuxexpo/scale-network#763]
## Description

Right now the IBM servers done have trays for some of drives

[IBM system x3650 tray](https://www.printables.com/model/263072-ibm-system-x3650-m4-25-tray)

## Acceptance Criteria
- Test print and fitment in x3650 server

**Comment by ptrlow1** [comment]
![PXL_20240922_223522587.jpg](https://github.com/user-attachments/assets/1de8cdb1-8c3e-4c33-bbb7-624e5a77ccf8)

![PXL_20240922_222204351.jpg](https://github.com/user-attachments/assets/9bd75c58-92e0-4d0a-a971-167f59381ff7)

Printed and tested to be working. (See the attached photos)

Would need to buy these screws to secure the drives to the 3D printed caddy:
uxcell 50pcs Hard Drive Screws M3 x 4.7mm HDD SSD Hard Drive Mounting Screws Black Metal Hard Drive Replacement Screws for Laptop Hard Drive 
> https://a.co/d/6cpOk39

**Comment by ptrlow1** [comment]
Installed the new trays in the 2 servers.
Used the screws that secure the SSDs in the caddy that were in screw bins @ Null Space Labs.

![PXL_20240922_232751343.jpg](https://github.com/user-attachments/assets/0a4c3948-e6b9-4350-bf4b-73824981a092)

Recommend to close this as completed.

**Comment by sarcasticadmin** [comment]
thank you very much @ptrlow1 the prints came out great!
