### ISSUE TITLE
(BUG) Potential privilege escalation on Pi images

### ISSUE THREAD

**Issue by ptrlow1** [socallinuxexpo/scale-network#766]
## Description
If pressing ALT+HOME (when a keyboard and mouse is connected to the Pi4) opens a new Chrome Incognito window, and clicking the gear in the "Block third-party cookies" section opens a new regular window, allowing someone to press F6 to access the address bar, which could allow for a arbatory command to be entered, or view files on the Pi's filesystem using "file:///" (example: "file:///etc/passwd" views the users on the system, etc.)

## Acceptance Criteria

- Disable the keyboard shortcut "ALT+HOME" to prevent someone from opening a Incognito window

~~Also disable Incognito mode completely, just for good measure~~
~~These sites have instructions on blocking Incognito mode:~~
~~https://askubuntu.com/questions/116319/how-to-disable-chromes-incognito-mode~~
~~https://thelinuxcode.com/turn-off-incognito-mode-google-chrome~~

Update: Incognito window is used, therefore ignore "Disable Incognito mode completely"

**Comment by sarcasticadmin** [comment]
Closed via https://github.com/socallinuxexpo/scale-kiosk/pull/7
