### ISSUE TITLE
reallocate switches

### ISSUE THREAD

**Issue by davidelang** [socallinuxexpo/scale-network#775]
organize the switches in numberic order in the carts

switches 1-11 noc cart
switches 12-23 lower conf cart
switches 24-39 expo cart
switches 40-51 ballroom cart
switch 52 monitor cart

new order is:

1 NOC
2 ConfIDF
3 NW-IDF
4 NE-IDF
5 ExpoIDF
6 Expo-Catwalk
7 MassFlash
8 AVSwitch
9 Rm209-210
10 Rm211
11 Rm214
12 Rm101-102
13 Rm103
14 Rm104
15 Rm105
16 Rm106
17 Rm107
18 SpareA
19 SpareB
20 SpareC
21 SpareD
22 SpareE
23 SpareF
24 ExpoAW
25 ExpoA1
26 ExpoA2
27 ExpoA3
28 ExpoA4
29 ExpoA5
30 ExpoB1
31 ExpoB2
32 ExpoB3
33 ExpoB4
34 ExpoB5
35 ExpoC1
36 ExpoC2
37 ExpoC3
38 ExpoC4
39 ExpoC5
40 BallroomA
41 BallroomB
42 BallroomC
43 BallroomDE
44 BallroomF
45 BallroomG
46 BallroomH
47 SpareG
48 SpareH
49 SpareI
50 SpareJ
51 SpareK
52 RegDesk

**Comment by davidelang** [comment]
@kylerisse  issue for the work you are doing.

**Comment by kylerisse** [comment]
https://gist.github.com/kylerisse/61cde5f50950b16f0901c2cf07429864
